name: Deploy Python Function to Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Ajusta la versión de Python según tus necesidades

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Check AzureWebJobsStorage configuration
        run: |
          az functionapp config appsettings list --name merch-bot --resource-group bot-rg
          az functionapp config appsettings set --name merch-bot --resource-group bot-rg --settings AzureWebJobsStorage=${{ secrets.AZURE_WEBJOBS_STORAGE }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'merch-bot'
          package: '.'
